name: a test workflow

on: 
  push: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ornladios/adios2:release_28-ubuntu-bionic
    steps:
      - name: Say hello
        run: echo "Hello"
