name: a test workflow

on: 
  push: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ornladios/adios2:release_28-ubuntu-bionic
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Say hello
        run: cat dummy_file.txt
